mozilla/arewefastyet

benchmarks/asmjs-ubench/fbirds-native.js, benchmarks/asmjs-ubench/fbirds-polyfill.js, driver/benchmarks.py
See also bug 1130827 on bugzilla.
Can be landed now.
=> SIMD: use load/store in the fbirds benchmark

benchmarks/asmjs-ubench/ecmascript_simd.js, benchmarks/asmjs-ubench/fbirds-native.js, benchmarks/asmjs-ubench/fbirds-polyfill.js, benchmarks/asmjs-ubench/mandelbrot-native.js, benchmarks/asmjs-ubench/mandelbrot-polyfill.js
Should be landed after bug 1129491 part 1 and 2 land. I'll ping you.
=> Simd Check

benchmarks/misc/tests/assorted/LIST, benchmarks/misc/tests/assorted/misc-basic-array-forof.js, browser-driver/benchmarks_shell.py, driver/benchmarks.py
This modification update misc-basic-array to be similar as the for-of and for-in tests, and to verify their results.  Thus we would be able to compare the performance of various each iterator loop against the basic-array.
=> new benchmarks for iterator loops.

benchmarks/asmjs-ubench/fbirds-native.js, benchmarks/asmjs-ubench/mandelbrot-native.js, driver/benchmarks.py
=> Update SIMD benchmarks to the latest SIMD.js SM updates

driver/submitter.py
This pull request add the `extraInfo` argument to the `AddTests` methods, and also to the `PrintSubmitter` methods as well.
cc @h4writer
=> Add extraInfo to the AddTests function.

README.md, detector/awfy.py, server/awfy-server.config, server/awfy.py, website/data.php, website/internals.php
Added Config Parser (similar to python scripts) for PHP. Now it reads all the configs from the same config file as python scripts do.
=> Move hard-coded configs to file.

database/migration-1.php, website/servo/frontpage.js, website/servo/index.html
Upstreaming all the changes in my `benchmarking-for-servo` branch.
All these commits have been reviewed when we merged them into `dhananjay92:benchmarking-for-servo`.
Now we can just have one master copy of AWFY that supports Servo as well.
=> Benchmarking for servo

benchmarks/kraken/sunspider-compare-results
Fixed the 'die at Line 110' error.
=> Make kraken/sunspider-conpare-results work.

benchmarks/misc/sunspider-compare-results
Imported and customized `sunspider-compare-results`.
=> Add compare script to misc benchmark

README.md
First commit is just cosmetic changes in the README.md file, wrapping all lines to 80 chars and adding a few usages of the code tags.
Second commit briefly explains what is AWFY at the top of the README.
r? @h4writer
=> Wrap readme and introduce AWFY

slave/download.py, slave/url_creator.py
I also include a change to determine the platform more accurately (needed in some cases).
r? @bnjbvr
=> Issue 130 - Add PGO support

database/migrate.php, database/migration-20.php, server/awfy.py, server/condenser.py, server/data.py, server/update.py
Opening a PR, but since it's trivial (only interesting change is at line 323 in update.py), merging. Feel free to have a look and suggest changes, though!
Already in production (sorry, that's bad open-sourcing...): https://arewefastyet.com/#machine=36&view=single&suite=speedometer-misc&subtest=score
=> Direction per subtest

slave/url_creator.py
This week we have switched Windows nightly builds to be generated on TaskCluster
rather than on Buildbot.
This requires some changes to the index used and the discovery of artifacts.
=> Bug 1385263 - Fix for TaskCluster migration

slave/task.py, website/regressions/js/controllers.js, website/regressions/partials/bug.html
This changes http references to arewefastyet.com to https. It does not change the values in website/regressions/js/app.js however.
=> Bug 1388817 - use https connections to arewefastyet.com, r=bbouvier

slave/url_creator.py, tests/test_url_creator.py
Fetching builds from Treeherder stopped working on August 18th.
Instead of trying to figure out what changed on Treeherder this change
switches AWFY to use the TaskCluster index which is easier to deal with.
This change also refactors test_url_creator to test more configurations
and have less lines of code.
=> Bug 1391587 - Refactor downloads of builds to use the TaskCluster index

website/awfy.js
By demand of :jonco.
Who doesn't love some jQuery from times to times?
@bclary, can you have a look, please?
=> Always open machines/breakdowns

website/lib/internals.php
I want to use awfy machines to test performance improvement/regression for WIP patches :)
=> Allow arai on tryserver

website/overview/css/main.css, website/overview/sass/partials/base/_header.scss, website/overview/sass/partials/components/pages/_main.scss
I promised to do this pull request 2 years ago or so, so let's finally do it :P
Is there any documentation about how to run the site locally to verify this fix?
=> Fix width of top bar on Overview page

slave/benchmarks_remote.py, slave/configs.py, slave/execute.py
This is still waiting on some information, but this part of the code is almost ready to land. Tested locally and it seems to generate different results when run with `-c webrender` or not.
=> Webrender + MotionMark

slave/configs.py
See announcement on dev platform and resolution of bug 1425260.
=> Simplify WebRender configuration
