mozilla/arewefastyet

- benchmarks/asmjs-ubench/fbirds-native.js
- benchmarks/asmjs-ubench/fbirds-polyfill.js
- driver/benchmarks.py
So I was investigating what wasn't going well with the fbirds benchmark. Actually, one branch was never taken because I've forgot to modify a few values when adapting the test case from Intel into a benchmark. This tiny update changes this and I've made sure that we go through all branches manually. With this change, type information in Ion is much better and we get a huge speedup.
Sorry about this, I know this is pretty bad to change the benchmark so many times, because it implies that the graph gets meaningless, but this should be one of the last changes, hopefully.
> fbirds: make the benchmark actually go through all code paths.

- driver/dorequests.py
- driver/dostuff.py
- driver/remotecontroller.py
- driver/slaves.py
- driver/submitter.py
With this pull request, there is a new option: --submitter (aka -s), which can take two values: 'remote' or 'print'. Default is 'remote'. When the submitter is set to remote, results will be sent to the AWFY php service, as it's done currently. When the submitter is set to print, results will be printed once we're done, which allows to run AWFY locally more easily.
> Make it possible to print results in the console rather than sending them to a distant endpoint.

- database/schema.sql
The error appears when I was trying to initialize a new awfy db:
'''
ERROR 1064 (42000) at line 170: You have an error in your SQL syntax;
check the manual that corresponds to your MySQL server version for the
right syntax to use near
') ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1'
at line 9
'''
> Fix a syntax bug in 'database/schema.sql'.

- database/schema.sql
'server/update.py' wants to access 'visible' field in 'awfy_suite',
which is absent in 'database/schema.sql'.
Computing master properties... Traceback (most recent call last):
File "/home/awfy/awfy/server/update.py", line 359, in <module>
main(sys.argv[1:])
File "/home/awfy/awfy/server/update.py", line 350, in main
cx = data.Context()
File "/home/awfy/awfy/server/data.py", line 164, in __init__
c.execute("SELECT id, name, description, better_direction, sort_order, visible FROM awfy_suite WHERE visible > 0")
File "/home/awfy/awfy/server/awfy.py", line 44, in execute
exe = self.cursor.execute(sql, data);
File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
self.errorhandler(self, exc, value)
File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, …
> Add 'visible' column to 'awfy_suite' table.

- driver/builders.py
TurboFan is enabled by default now and is used selectively. The results for v8-turbofan are not relevant to released code and cause a lot of noise in the AWFY results.
What I am not sure about is how to remove the existing plot from the graphs?
> Remove the v8-trubofan mode from testing.

- benchmarks/misc/tests/assorted/LIST
- benchmarks/misc/tests/assorted/misc-basic-hoist-bounds-check.js
- browser-driver/benchmarks_shell.py
- driver/benchmarks.py
Add a ~25ms - ~30ms  micro benchmark which verifies that we do hoist-bounds-check ([Bug 1158344](bugzil.la/1158344)).
> Add micro benchmarks to verify that we hoist bound checks.

- driver/builders.py
This is the configuration that we intend to ship at some point. The
--turbo flag is a meta flag that enables everything required to run
TurboFan in a sane way.
> Add correct v8-turbofan configuration.

- slave/runners.py
Wait for killall to finish, else it ends up killing other instances created right after killall().
Since `killall()` doesn't wait for killall command to finish, it ends up killing the same processes spawned in near-future. See [this comment](https://github.com/dhananjay92/arewefastyet/issues/1#issuecomment-143049199) for some context. 
**Example:** In [ServoExecutor](https://github.com/dhananjay92/arewefastyet/commit/01f6a9#diff-975a8528dda6ea0a1090e7df97de1177R91), first we call [`killall()`](https://github.com/dhananjay92/arewefastyet/commit/01f6a9#diff-975a8528dda6ea0a1090e7df97de1177R100) and then [`runner.start()`](https://github.com/dhananjay92/arewefastyet/commit/01f6a9#diff-975a8528dda6ea0a1090e7df97de1177R106) is called. But that process gives -15 as error code. See [full …
> Wait for killall to finish.

- benchmarks/misc/tests/assorted/misc-apply-array-headroom.js
- benchmarks/misc/tests/assorted/misc-apply-array.js
Moving performance tests from jit-test to AWFY, on bbouvier's suggestion: https://bugzilla.mozilla.org/show_bug.cgi?id=1228421#c3.
> Benchmarks for the fun.apply(...,array) optimization

- benchmarks/asmjs-ubench/fbirds-native.js
- benchmarks/asmjs-ubench/mandelbrot-native.js
Firefox nightly is now (Bug 1160971) following the current SIMD.js spec which
includes boolean SIMD types, and the SIMD.Float32x4.lessThanOrEqual function is
returning a Bool32x4 instead of an Int32x4.
Update the two native SIMD tests to expect this return type.
> Update asm.js SIMD tests to the latest SIMD.js spec.

- benchmarks/webaudio/benchmarks.js
- slave/benchmarks_local.py
This pulls in the updated benchmarks.js from padenot/webaudio-benchmark
as of revision b93e344b2f00e4eb3b758b2fdf7f97abf0c99bf5. The changes to
the grafana files are not relevant to AWFY.
> Update webaudio benchmark to upstream revision b93e344

- slave/download.py
- slave/utils.py
- treeherder/submission.py
In bug 1230222 we're encouraging consumers of Treeherder's API to set user agent:
https://bugzilla.mozilla.org/show_bug.cgi?id=1230222
Ideally the two definitions of the user agent in this PR would be combined, however the current repo structure (lack of modules), sys.path manipulation and mixture of requests and urllib2, means it would involve a bit of refactoring, so this small bit of duplication seems fine for now.
> Add a user agent to requests made to Treeherder's API

- benchmarks/SunSpider/sunspider-compare-results
- benchmarks/kraken/sunspider-compare-results
- benchmarks/misc-desktop/sunspider-compare-results
- benchmarks/misc/sunspider-compare-results
Sometime I would like to set a result filename (.js) as baseline.
After I modified the file 'baseline-filename.txt' a newline charactor
was usually introduced, which broke the compare-results script.
It usually dies at line 70, complaining 'no such file.'
> Chomp the string read from 'baseline-filename.'

- slave/build.py
SmallPage.h has been renamed SmallRun.h in http://trac.webkit.org/changeset/197955
> SmallPage.h has been renamed SmallRun.h in r197955

- benchmarks/misc/tests/assorted/LIST
- benchmarks/misc/tests/assorted/misc-map-iterator.js
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1248289
There I'm going to inline `_GetNextMapEntryForIterator` intrinsic, that is used in `%MapIteratorPrototype%.next`.
The inlined `_GetNextMapEntryForIterator` supports only boxed array for `mapIterationResultPair` (the temporary array to receive key-value pair from native function), and I expect some performance regression when unboxed array is enabled, and it's somehow used as `mapIterationResultPair` array (created in `MapIteratorObject::createResultPair`), as inlined code will be no more used for that case.
Locally, the inlining patch improves the score of this test from 252.0ms to 89.2ms.  So once this inlining become inapplicable, the score will be regressed to similar score as before.
To track it, I'd like to add this …
> Add map iterator to misc benchmark.

- slave/configs.py
- slave/execute.py
This enabled Branch Pruning to make sure we can compare and tune our heuristics before landing.
Note, as opposed to flowAA, I wanted to enable it on dromaeo as well as the shell, so I am using the environment variable instead of the command line option.
cc @h4writer
> Add branch pruning config

- .gitignore
- slave/benchmarks.py
- slave/benchmarks_remote.py
- slave/configs.py
- slave/download.py
- slave/execute.py
- slave/executors.py
- slave/server.py
- slave/submitter.py
- slave/url_creator.py
- Commit 1 reorders imports in a few files, with the following rule: first system namespace imports, then specific system imports, then local imports. It helps knowing what's local and what's not. There are a few logical cleanups too.
- Commit 2: adds a static method name() for the remote benchmarks, so that it's easier to add one
- Commit 3: adds a remote wasm benchmark and sets the about:config pref to enable wasm.
@h4writer, can you have a look, please?
There's something I haven't done and that I wish too: only Firefox should run the wasm benchmark (yet) because other browsers might need something special to enable wasm support; and only the default Firefox mode (so no no-asmjs etc.) should be used. Is there a way I can programatically do this, or does it belong to the slave-specific …
> A few cleanups and a new remote benchmark

- benchmarks/six-speed/test.js
Using new Date() in the subtraction adds the time required to convert a
Date object to a Number to the measurement, which is not necessarily
what you want to measure, especially with micro benchmarks like these.
> [six-speed] Use Date.now() instead of new Date().

- slave/executors.py
By default, Chromium uses a user data directory (think: profile directory for Chromium) that's outside our reach. I think that using a temporary directory and removing it between runs should lower the risk of incorrect browser cache hits. Here's a patch that implements that.
Also, just for sanity, the URL is appended after all other arguments in the BrowserExecutor. This removes the suspicion that args after the URL are ignored.
> Use a temporary user directory for Chromium

- slave/benchmarks.py
- slave/benchmarks_local.py
- slave/benchmarks_remote.py
- slave/execute.py
- slave/server.py
This removes the hacky starting of the proxy server, by running it before starting any benchmark and closing it properly in all the cases. It bite me a few times that a proxy server was running in the background while the execute script had terminated, showing cached versions of benchmarks I was trying to update.
@h4writer In your own time, would you please have a look? This works fine locally, fwiw.
> Properly start and exit the proxy server before running the benchmarks

- slave/download.py
- slave/url_creator.py
Recently, we made TaskCluster cross-compiled Mac builds on trunk trees
into tier 1 platforms. These replaced the Buildbot builds.
On older release branches we also made a change where a Buildbot build
is driven by TaskCluster via the Buildbot bridge. The Buildbot bridge
schedules normal Buildbot jobs. The Buildbot bridge also sets a
property called 'upload_to_task_id'. This task id is used to create
a TaskCluster task and upload there the build artifacts. Using this
will help us not have to deal with archive.mozilla.org at all.
> Mac downloads to support TaskCluster and Buildbot bridge

- slave/download.py
- slave/url_creator.py
- tests/test_url_creator.py
The following commits:
- change a few names to be more pythonic (with camel_casing)
- add more Mozilla downloads for release/beta, where the N symbol is sometimes used in place of the B/Bo symbols (and the filename in the url is `firefox-{VERSION_NUMBER}.{SOMETHING}.{PLATFORM}.zip` in this case)
- update the `url_creator` tests and add the ability to create URLs for another platform than the current one
@armenzg, can you have a look please? Thanks!
> Test downloads more effectively

- slave/url_creator.py
- tests/test_url_creator.py
r? @bnjbvr 
I've tested this for macosx64, win32 and win64.
The change does not support Linux. This can come later.
FYI macosx64 builds are still downloading the Buildbot version.
https://bugzilla.mozilla.org/show_bug.cgi?id=1377114
When the bug gets fixed we will have to adjust which will also fix the Linux situation.
> Issue 138 - Support for downloading nightly builds

- slave/configs.py
- slave/executors.py
The first commit changes from using a string of user_pref values in profile_ to keeping the preferences in a dictionary that is passed to FirefoxProfile to create the profile. See the bug for more details.
The second commit adds the preference prefs["layout.css.servo.enabled"] = False to prevent servo from running.
> Bug 1390206 profile

- slave/url_creator.py
- tests/test_url_creator.py
It would support work being done in bug 1393068. I just tweaked the url_creator script and it happens to pass all the tests, which is awesome, thanks to @armenzg recent work. Can you have a look, please?
(cc @bclary)
> Support autoland in the list of Mozilla repositories;

- slave/benchmarks_remote.py
https://mozilla.github.io/arewefastyet-speedometer/2.0/ is already updated to r221659
Most important change is switch to geometric mean: https://trac.webkit.org/changeset/221659/webkit
> Speedometer update

- treeherder/submission.py
**1) Stop using deprecated TreeherderClient protocol/host arguments**
They've been replaced with `server_url` instead (which should be of form `https://treeherder.mozilla.org` with no trailing slash).
**2) Use TreeherderClient's `add_revision()` instead of `add_revision_hash()`**
Since the latter has been deprecated for some time, and now removed in the latest treeherder-client release. It is no longer necessary to perform the separate lookup to map a revision to the revision hash.
Fixes #154.
----
**NB: Before deploying:**
* check that the treeherder `host` config key set in the local `awfy-server.config` file on the server is of the correct form (ie no trailing slash). 
* update to the latest treeherder-client
- the comment in submission.py says to use `sudo` (sidenote: this is not …
> Support newer treeherder-client

- slave/configs.py
- slave/execute.py
- slave/submitter.py
In addition to this, I will:
- change the control tasks in the DB so:
1. they don't pass the `submitter-mode` flag for all the runs.
2. they don't define the `-c wasm` since it is available by default everywhere nowadays.
- create a new DB entry in `awfy-mode` to describe the `v8-liftoff` line (choose a color, etc).
Bob, can you have a look please? Thanks!
> Add support for v8's liftoff

- slave/benchmarks_local.py
- slave/benchmarks_remote.py
- slave/benchmarks_shell.py
- slave/build.py
- slave/configs.py
- slave/download.py
- slave/execute.py
- slave/executors.py
- slave/puller.py
- slave/run-task.sh
- slave/runners.py
- slave/server.py
- slave/submitter.py
- slave/task.py
- slave/url_creator.py
- slave/utils.py
Change slave/run-task.sh to the standard run script. This will require:
- either ~/AWFY_CONFIG containing export CONTROL_UNIT_ID=id or
CONTROL_UNIT_ID already in the environment.
- arewefastyet checked out to ~/arewefastyet
Once these conditions are met, start the script via
~/arewefastyet/slave/run-task.sh
Second, we change the print statements currently used to log to
stdout to use a set of functions which will continue to print to
stdout but also will log to a rotating log file controlled by the
main process. This log file will be shared by the main and child
processes but only the main process in task.py will be able to
rotate the log.
Lastly, we fix a number of pyflakes warnings though not all.
> Bug 1422887 improve log handling
